#!/bin/bash
usage="Usage: net-out"


if [ $# -ne 0 ] && [ $# -ne 1 ]
then
    echo $usage; exit 1
fi 

if [ $# -eq 1 ]
then
    time=$1
    watch -n$time $(realpath $0) #ruta absoluta del script
fi
num_paq_totals=0
cat /proc/net/dev | tail -n2 | awk '{print $1, $3}'
for num_paq_interf in $(cat /proc/net/dev | tail -n2 | awk '{print $3}')
do
    num_paq_totals=$(echo "$num_paq_totals+$num_paq_interf" | bc -l )
done

echo "Total: $num_paq_totals"
